### ISSUE TITLE
(36) TestErgebnisse persistent

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#122]
Beschreibung:
Zurzeit gehen alle Testergebnisse nach dem beenden des Server verloren.

Der User soll aber auch nach einem Neustart noch auf die Testergebnisse zugriff haben.

Akzeptanzkriterium:

**Comment by Sniger87** [comment]
import dbm

with dbm.open() as db:
 db[''] = 
db.keys
value = db['']
