### ISSUE TITLE
Probleme mit dem 2. Router (?)

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#127]
der erste Router muss zurück geflasht werden auf "stable"

**Comment by Symen** [comment]
sollte er eigentlich schon sein. Hatte am Montag eine stable Firmware draufgespielt.

**Comment by P8H** [comment]
ok, danke.

Dann liegt es wohl doch an etwas anderem. Ich evaluiere das erstmal noch am Montag..
Anscheinend bestehen Probleme mit einem Router.

**Comment by P8H** [comment]
nach einem Neustart der Router funktionieren wieder beide...
