### ISSUE TITLE
Steckerleiste IP Einstellung

### ISSUE THREAD

**Issue by acid-horny** [PumucklOnTheAir/TestFramework#128]
Nach Ausführen von server_start.py funktioniert das Ansteuern der Steckerleiste nicht. "sudo ip netns exec nsp20 ifconfig vlan20 192.168.1.2/24 up" behebt das Problem.
(getestet auf Branch #35)

**Comment by Symen** [comment]
Merge bitte vorher nochmal deinen Branch mit dem Master, ich glaub du hast noch nicht die aktuelle Version.
