### ISSUE TITLE
unstable ssh connections

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#131]
Beobachtung:
SSH Session sind sehr langsam und hängen sich auf. Das selbe gilt für PyCharm Remote Prozeduren.

Sehr schön beobachtbar ist das, wenn man den Pi *anpingt*.

Bisherige Analyse:

**Comment by P8H** [comment]
im commit #be6f1d4 existiert der Bug auch, allerdings nur zur init Zeit. Vermutlich besteht ein Zusammenhang mit den Namespace/VLAN da sie in dieser Version jedesmal abgebaut werden nach einem ausgeführtem Job.

**Comment by P8H** [comment]
im aktuellem master (8d1c52e) funktioniert es die ganze Zeit nicht, so lange der Server läuft. Nach dem beenden des Servers, ist der ping wieder stabil.

**Comment by P8H** [comment]
habe ein Namespace erstellt nach der Anleitung im Wiki.
(https://github.com/PumucklOnTheAir/TestFramework/wiki/Create-VLan-and-Namespace-by-console)

Allerdings konnte das nicht den Fehler reproduzieren.

**Comment by Symen** [comment]
Bei mir funktionieren alle Funktionen im Master bzw. hab update_info, online, reboot, ausprobiert und keine Errors bekommen. Router wurden auch korrekt neugestartet.

**Comment by P8H** [comment]
Fehler unabhängig von den Funktionen vom Framework. Framework muss bloß gestartet sein, um die Symptome zu erzeugen.

**Comment by P8H** [comment]
nicht mehr reproduziebar..
