### ISSUE TITLE
Config Schema validation

### ISSUE THREAD

**Issue by andir** [PumucklOnTheAir/TestFramework#133]
leider etwas verspaetet der Link zur schemavalidation:

https://python-jsonschema.readthedocs.org/en/latest/

Natuerlich ersetzt das nicht testen der schema. Also ihr muesst dann auch mal invaliden Kram in die Tests stecken und es muss fehlschlagen. Aber es sollte so Dingen wie `assert len(config) == 0` vermeiden.

**Comment by Sniger87** [comment]
danke dir schau es mir gleich mal
