### ISSUE TITLE
Update info und update online nach jedem Task ?

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#137]
Es ist zu Prüfen, ob nicht Update Info oder Update Online öfters ausgeführt werden kann/sollte um die Daten aktuell zu halten.

Ggf. daraus eine User Story erstellen.

**Comment by Symen** [comment]
Ich glaub das sollte man davon abhängig machen, ob sich der Zustand des Routers geändert haben kann. Ansonsten brauch es mehr Zeit die Infos zu updaten, als der eigentliche Task. Wenn wir z.B. mehrere Tests hintereinander durchlaufen lassen die alle vorhandene Infos nutzen, macht es wenig Sinn immer wieder die gleichen Daten anzufordern.

**Comment by P8H** [comment]
ergo. möglicher  "best practice" ansatz:  Update_Info kann nur noch bewusst als fremd modul aufgerufen werden im Test.
