### ISSUE TITLE
Email Infos in Config-File

### ISSUE THREAD

**Issue by Symen** [PumucklOnTheAir/TestFramework#165]
Key: Value
smtp_server: 'smtp.web.de'
smtp_port: 587
email: 'symenschmitt_trash@web.de'
email_password: 'passworder'
key_email: 'keys@darmstadt.freifunk.net'

**Comment by Symen** [comment]
kann im branch register_public-key-#163 gemacht werden

**Comment by Sniger87** [comment]
Ich setze die Infos in die Server config

**Comment by Sniger87** [comment]
ConfigManager.get_server_property("Key")
zum abrufen der neuen Einträge
oder über ConfigManager.get_server_dict() oder ConfigManager.get_server_list()

ist in den Branch #163 commited
