### ISSUE TITLE
Logging von Paramiko und Selenium deaktivieren

### ISSUE THREAD

**Issue by Symen** [PumucklOnTheAir/TestFramework#166]
Einfach mal nachgucken ob man den Logger für paramiko und selenium deaktivieren kann oder zumindest auf einen Level setzt, dass unsere Ausgaben nicht mehr gestört werden.

**Comment by Sniger87** [comment]
import logging
selenium_logger = logging.getLogger('selenium.webdriver.remote.remote_connection')
# Only display possible problems
selenium_logger.setLevel(logging.WARNING)

import paramiko
import logging
logger = paramiko.util.logging.getLogger()
logger.setLevel(logging.WARN)

**Comment by Symen** [comment]
Danke. Werds mal ausprobieren.

**Comment by Sniger87** [comment]
ne Simon sollst du gar nicht ausprobieren
hab ich als Erinnerung an mich da rein gepackt
