### ISSUE TITLE
Neues CLI-Kommando: register_key

### ISSUE THREAD

**Issue by Symen** [PumucklOnTheAir/TestFramework#167]
Mit folgenden Argumenten:

-a : für alle Router
-r \<id\> \<id\> ... : für bestimmte Router

soll die Funktion 

register_key(router_ids, register_all)

im Server aufrufen. (Zurzeit noch in Branch register_public-key-#163)

**Comment by Symen** [comment]
kann direkt im branch 'register_public-key-#163' gemacht werden

**Comment by acid-horny** [comment]
resolved in PR #174
