### ISSUE TITLE
Keine Ausgabe der SubProzesse auf der CLI

### ISSUE THREAD

**Issue by Symen** [PumucklOnTheAir/TestFramework#188]
Führt man z.B. 

`python3 cli.py online -r 0`

aus, wird auf der Konsole der CLI nur das ausgegeben was vom Server-Prozess kommt. Erst nach mehrmaligem aufrufen des genannten Befehls werden auch Ausgaben der Child-Prozesse angezeigt.

**Comment by Symen** [comment]
Lässt man sich in einer run-Funktion einer der util-Klassen die Handler des Loggers ausgeben kann man sehen, dass ein Handler fehlt. Bzw. sobald auf der CLI-Konsole die richtigen Ausgaben sichtbar sind gibt es einen Handler mehr.

**Comment by Symen** [comment]
Schreibt man die gewünschte Konsole direkt ins LoggerSetup funktioniert es. Man könnte also zu Beginn auch alle Konsolen bestimmen die aktive sind (im terminal z.B. mit 'who'. Geht in python sicher auch irgendwie) und diese dann direkt hinzufügen. Vorteil wäre die CLI müsste nicht vor jedem Befehl die Konsole registrieren. Nachteil, wir haben eine Ausgabe auf allen Konsolen.

**Comment by Sniger87** [comment]
gleich reinschreiben finde ich keine gute idee, da wie du schon geschrieben hast dann alles auf jeder konsole ist
Ich debugge das morgen mal direkt auf dem PI und schau mal wo es da beim registrieren fehlt schlägt, wobei das ja anscheinden wieder nur sporadisch passiert

**Comment by Symen** [comment]
Problem ist registriert wird es ja, sonst bekämen wir ja überhaupt keine Ausgabe auf der CLI-Konsole. Aber anscheinend greifen die Logging-Funktionen in den Child-Prozessen auf eine 'veraltete'-Version des Loggers zu. Anders kann ich mir das Verhalten nicht erklären.

**Comment by Symen** [comment]
Wie lange soll eigentlich der Thread im MultiProcessingHandler laufen? Also nach meinem Verständnis müsste er eigentlich bis zum Ende laufen. Allerdings wird die Funktion 'receive' die der Thread aufruft nicht so lange ausgeführt wie erwartet sondern vorher beendet. Was glaub ich dazu führt, dass log-results die gesendet werden nicht ausgegeben werden.
