### ISSUE TITLE
(14) Grundgerüst Tests

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#3]
Ein Grundgerüst für die Tests anlegen. 

Im Server wird ein ThreadPool (?) angelegt, worin die Tests einzeln laufen.

- [x] Abstrakte Klasse Test
- [x] Beispiel Test anlegen und hardcoded integrieren
- [x]  Werte/Router wird an den Test übergeben 
- [x] ProcessPool im Server anlegen
- [x] Test kann im Server gestartet
- [x]  Alle Tests können abgebrochen werden
- [x] Einfache Rückgabe der *Ergebnisse* (true, false oder so)
- [x] Tests laufen im richtigem VLAN
- [x] + abstrakte Job-Funktionalität

In weiteren UserStories geht es um die Verwaltung der Tests und Ergebnisse (Reports)

**Comment by P8H** [comment]
womöglich interessant für dich 
https://docs.python.org/2/library/ipc.html

**Comment by P8H** [comment]
Prozesse nutzen statt Threads, wegen VLAN

**Comment by P8H** [comment]
tests schlagen auf dem raspberry pi fehl

Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/home/pi/TestFramework_1/server/server.py", line 193, in _test_done
    cls.__start_task(task.router, None)
  File "/home/pi/TestFramework_1/server/server.py", line 132, in __start_task
    task = cls.executor.submit(cls._execute_test, job, router)
  File "/usr/lib/python3.4/concurrent/futures/process.py", line 396, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown

**Comment by P8H** [comment]
python3.4 -m unittest framework_unittests/test_Server_2.py

**Comment by P8H** [comment]
Ordner TestFramework_1 auf dem Pi

**Comment by Symen** [comment]
NVAssistent.create_namespace_vlan_veth(router) sollte jetzt verwendet werden, um in einem neuen Prozess VLANs zu nutzen.

**Comment by P8H** [comment]
NVAssistent.create_namespace_vlan_veth(router) sollte wohl eher ein _RemoteSystem_ als parameter haben oder @Symen ?

**Comment by P8H** [comment]
und zum schluss nv_assi.close() aufrufen? @Symen
