### ISSUE TITLE
(11) Logging

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#32]
- [ ] Logging Konfiguration implementieren.
- [ ] Andere Teammitglieder einweisen 

https://github.com/PumucklOnTheAir/TestFramework/wiki/Logging

**Comment by Sniger87** [comment]
http://victorlin.me/posts/2012/08/26/good-logging-practice-in-python

https://docs.python.org/3.5/library/logging.html#logging.Logger
