### ISSUE TITLE
(23) Router Web-Konfigurationsassistent einbinden

### ISSUE THREAD

**Issue by Symen** [PumucklOnTheAir/TestFramework#62]
Nach einem "sysupgrade" kann nicht mehr direkt auf den Router zugegriffen werden. Hier für muss der Router erst wieder über das WebInterface konfiguriert werden.

Verwendet werden soll hier "Selenium"

**Comment by P8H** [comment]
Hab es mal umbenannt, jetzt ist es etwas eindeutiger. Hab zuerst gedacht, es geht um das WebInterface vom TestFramework.

**Comment by Symen** [comment]
Ja ist in Ordnung. Werd die user story auch noch anpassen.
