### ISSUE TITLE
Logger setup automatisieren

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#63]
Nach der Doku muss ja zuvor Logger().setup() aufgerufen werden um den Logger zu verwenden.

Kann man das nicht womöglich auslagern direkt in die Logger Datei? Beim Import müsste doch dann der Logger automatisch das Setup ausgeführt haben

**Comment by Sniger87** [comment]
Wird automatisch schon ausgeführt. Logger.setup() kann aufgerufen werden und andere Werte initialisiert werden
