### ISSUE TITLE
(23.1) CLI - Neues Kommando

### ISSUE THREAD

**Issue by Symen** [PumucklOnTheAir/TestFramework#69]
- [x] Der Befehl "cli.py webconfig setup" soll die Funktion
"server.setup_web_configuration(router_ids: List[int],  setup_all: bool)" 
aufrufen.

- [ ] Der Befehl "cli.py webconfig reset" soll die Funktion 
"server.reset_web_configuration(router_ids: List[int],  reset_all: bool)"
aufrufen.

- [x] Der Befehl "cli.py reboot configmode" soll die Funktion
"server.reboot_router(router_ids: List[int],  reset_all: bool, True)"
aufrufen

- [x] Der Befehl "cli.py reboot" soll die Funktion
"server.reboot_router(router_ids: List[int],  reset_all: bool, False)"
aufrufen

**Comment by Symen** [comment]
Die beiden Funktionen sind noch nicht im master-branch, kommen aber die Tage.

**Comment by acid-horny** [comment]
kann mit branch #62 gemerged werden, befehle vollständig
