### ISSUE TITLE
test_firmware_handler.py overtime

### ISSUE THREAD

**Issue by P8H** [PumucklOnTheAir/TestFramework#75]
tests/test_firmware_handler.py benötigt ziemlich viel Zeit (manchmal mehr als 2 Min) auf Travis CI.

Muss das sein?
Man kann auf travis z.B. einstellen das bestimmte Ordner/Dateien gecacht werden. Würde das Helfen oder den Test nutzlos machen?

**Comment by P8H** [comment]
es liegt am neuem py.test..
https://travis-ci.org/PumucklOnTheAir/TestFramework/builds/102102326
https://travis-ci.org/PumucklOnTheAir/TestFramework/builds/101617549

oder dass der File Server uns geblockt hat :))

**Comment by P8H** [comment]
lag wohl doch eher am coverage test tool

**Comment by Symen** [comment]
also test_firmware_handler.py kann durchaus lange dauern, kommt drauf an ob alle "Images" runtergeladen werden sollen.

**Comment by Symen** [comment]
der Wert download_all sollte eigentlich aber auf False gesetz sein, so dass nur ein "Image" runtergeladen wird
